# Generated by Django 5.1.5 on 2025-01-15 17:17

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=courses.models.handle_upload)),
                ('status', models.CharField(choices=[('pub', 'Published'), ('coming_soon', 'Coming Soon'), ('draft', 'Draft')], default='draft', max_length=12)),
                ('access', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=10)),
            ],
        ),
    ]
