# Generated by Django 5.1.5 on 2025-01-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='can_preview',
            field=models.BooleanField(default=False, help_text='If user does not have access to the course, can they preview the lesson?'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('pub', 'Published'), ('coming_soon', 'Coming Soon'), ('draft', 'Draft')], default='pub', max_length=12),
        ),
    ]
